### PR TITLE
Update Email Templates

### PR DESCRIPTION
**Pull request by halimekarayay**
Resolves https://github.com/volosoft/eventhub/issues/30

### CODE REVIEW

**Comment by EngincanV** [comment]
## Email templates 

### Event Registration

event-registration

### Event Reminder

event-reminder

**Review by EngincanV — COMMENTED** [review]
Email Templates: https://github.com/volosoft/eventhub/pull/106#issuecomment-1126132068

I think we should focus on the main point of the email. I mean for the **EventRegistration** email, we should say something like "You've registered an event ...".

For both templates, they are almost identical and do not focus on their purpose.

**Review by EngincanV — APPROVED** [review]

**Comment by EngincanV** [comment]
@gizemmutukurt, can you test the email templates, please? Then, you can merge this PR.

**Comment by gizemmutukurt** [comment]
- Detail button can be minimized
- The following icons and footer proportions should be arranged.

image

**Comment by halimekarayay** [comment]
@gizemmutukurt I fixed the bugs.. Can you test again?

**Comment by gizemmutukurt** [comment]
OK.

image

**Review by gizemmutukurt — APPROVED** [review]

**Pull request merged**
